server:
  port: 8090


spring:
  datasource:
    username: "macroswebapp"
    password: "M4cr0sw3b4pp*2022"
    url: "jdbc:sqlserver://dwh.cbolivar.com:13144;databaseName=MacrosWebApp"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect